/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygym.presentacion.forms;

import java.awt.Color;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mygym.logica.usuario.dataTypes.DtCuponera;
import mygym.logica.usuario.dataTypes.DtCuponeraDetalle;
import mygym.logica.usuario.dataTypes.DtInstitucion;

/**
 *
 * @author mandi
 */
public class addActividadtoCuponera extends javax.swing.JFrame {
    
    public static HashMap<Integer, DtInstitucion> institucionesSistema = new HashMap<Integer, DtInstitucion>(); // ELIMINAR
    
    
    /**
     * Creates new form agregarActividadACuponera
     */
    public addActividadtoCuponera() {
        initComponents();
        DtInstitucion ins1 = new DtInstitucion("Sede Nacional", "La sede de Nacional", "https://nacional.com");
        DtInstitucion ins2 = new DtInstitucion("Sede Peñarol", "La sede de Peñarol", "https://Peñarol.com");
        agregarElemTabla(ins1);
        agregarElemTabla(ins2);
        
        llenarTabla();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaInstituciones = new javax.swing.JTable();
        btnSeleccionarInstitucionBG = new javax.swing.JPanel();
        btnSeleccionarInstitucion = new javax.swing.JLabel();
        cmbActividades = new javax.swing.JComboBox<>();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Actividad Deportiva a Cuponera");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(4, 37, 58));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Instituciones");
        jPanel1.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 29));

        scrollTabla.setBackground(new java.awt.Color(255, 255, 255));
        scrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        scrollTabla.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tablaInstituciones.setAutoCreateRowSorter(true);
        tablaInstituciones.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tablaInstituciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInstituciones.setGridColor(new java.awt.Color(255, 255, 255));
        tablaInstituciones.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tablaInstituciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInstitucionesMouseClicked(evt);
            }
        });
        scrollTabla.setViewportView(tablaInstituciones);

        jPanel1.add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 290));

        btnSeleccionarInstitucionBG.setBackground(new java.awt.Color(76, 131, 122));

        btnSeleccionarInstitucion.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnSeleccionarInstitucion.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarInstitucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionarInstitucion.setText("Seleccionar");
        btnSeleccionarInstitucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarInstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarInstitucionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSeleccionarInstitucionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSeleccionarInstitucionMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnSeleccionarInstitucionBGLayout = new javax.swing.GroupLayout(btnSeleccionarInstitucionBG);
        btnSeleccionarInstitucionBG.setLayout(btnSeleccionarInstitucionBGLayout);
        btnSeleccionarInstitucionBGLayout.setHorizontalGroup(
            btnSeleccionarInstitucionBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSeleccionarInstitucionBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeleccionarInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSeleccionarInstitucionBGLayout.setVerticalGroup(
            btnSeleccionarInstitucionBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSeleccionarInstitucionBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeleccionarInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSeleccionarInstitucionBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        cmbActividades.setBorder(null);
        jPanel1.add(cmbActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 150, -1));

        lblInfo.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Actividades disponibles: (que no están en esta Cuponera)");
        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 670, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void llenarTabla(){
        DefaultTableModel modeloDatos = (DefaultTableModel) tablaInstituciones.getModel();
        for (int i = 0; i < institucionesSistema.size(); i++){
            DtInstitucion currentInstitucion = institucionesSistema.get(i);
            //modeloDatos.addRow(new Object [] {currentCuponera.getNombre(), currentCuponera.getDescripcion(), currentCuponera.getDescuento()});           
            modeloDatos.setValueAt(currentInstitucion.getNombre(), i, 0);
            modeloDatos.setValueAt(currentInstitucion.getDescripcion(), i, 1);
        }
    }

    public static void agregarElemTabla(DtInstitucion x){
        int idHashMap = institucionesSistema.size();
        institucionesSistema.put(idHashMap, x);
    }
    
    private void btnSeleccionarInstitucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarInstitucionMouseClicked

    }//GEN-LAST:event_btnSeleccionarInstitucionMouseClicked

    private void btnSeleccionarInstitucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarInstitucionMousePressed
        btnSeleccionarInstitucionBG.setBackground(new Color(103, 149, 142));
    }//GEN-LAST:event_btnSeleccionarInstitucionMousePressed

    private void btnSeleccionarInstitucionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarInstitucionMouseReleased
        btnSeleccionarInstitucionBG.setBackground(new Color(76,131,122));
    }//GEN-LAST:event_btnSeleccionarInstitucionMouseReleased

    private void tablaInstitucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInstitucionesMouseClicked
        // TODO add your handling code here:
        int selectedRowId = tablaInstituciones.getSelectedRow();
        
        DtInstitucion selectedInst = institucionesSistema.get(selectedRowId);
        if (selectedInst != null){
            cmbActividades.removeAllItems(); // Primero elimino todos los elems del combobox, para que solo se vean los de la institución seleccionada en el grid.
            cmbActividades.addItem(selectedInst.getNombre());
            //JOptionPane.showMessageDialog(new JFrame(), "Institucion seleccionada: " + selectedInst.getNombre(), "Cuponera seleccionada", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "Error, seleccione una cuponera existente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        /*  *************************COMBOBOX*************************
        for (int i = 0; i < institucionesSistema.size(); i++){
            DtActividad act1 = new DtActividad("Natación", "Actividad de nado.", 60, 1500, new Date(08-09-2022));
            cmbActividades.addItem(selectedInst.getNombre());
        }
        */
    }//GEN-LAST:event_tablaInstitucionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addActividadtoCuponera().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSeleccionarInstitucion;
    private javax.swing.JPanel btnSeleccionarInstitucionBG;
    private javax.swing.JComboBox<String> cmbActividades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaInstituciones;
    // End of variables declaration//GEN-END:variables
}
