/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygym.presentacion.forms;

import java.awt.Color;

/**
 *
 * @author mandi
 */
public class crearCuponeraForm extends javax.swing.JFrame {

    /**
     * Creates new form crearCuponeraForm
     */
    public crearCuponeraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserInicio = new com.raven.datechooser.DateChooser();
        dateChooserFin = new com.raven.datechooser.DateChooser();
        jPanel2 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblDescuento = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDescripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JTextField();
        txtFin = new javax.swing.JTextField();
        btnCrearBG = new javax.swing.JPanel();
        btnCrear = new javax.swing.JLabel();

        dateChooserInicio.setToolTipText("");
        dateChooserInicio.setName(""); // NOI18N
        dateChooserInicio.setTextRefernce(txtInicio);

        dateChooserFin.setTextRefernce(txtFin);

        setTitle("Crear cuponera");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 540));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(4, 37, 58));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Crear Cuponera");
        jPanel2.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 29));

        lblNombre.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, 30));

        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese un nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, 20));

        lblDescuento.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblDescuento.setText("Descuento (%)");
        jPanel2.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        txtDescuento.setForeground(new java.awt.Color(204, 204, 204));
        txtDescuento.setText("Ingrese el porcentaje a descontar");
        txtDescuento.setToolTipText("");
        txtDescuento.setBorder(null);
        txtDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescuentoMousePressed(evt);
            }
        });
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        jPanel2.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 210, 20));

        lblDescripcion.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción");
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 80, 30));

        txtareaDescripcion.setColumns(20);
        txtareaDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        txtareaDescripcion.setLineWrap(true);
        txtareaDescripcion.setRows(5);
        txtareaDescripcion.setText("Ingrese una descripción");
        txtareaDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtareaDescripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtareaDescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 320, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Período de Vigencia"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Inicio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de Fin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInicioMouseClicked(evt);
            }
        });
        jPanel1.add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 170, -1));
        jPanel1.add(txtFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 320, 120));

        btnCrearBG.setBackground(new java.awt.Color(76, 131, 122));

        btnCrear.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrear.setText("CREAR");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCrearBGLayout = new javax.swing.GroupLayout(btnCrearBG);
        btnCrearBG.setLayout(btnCrearBGLayout);
        btnCrearBGLayout.setHorizontalGroup(
            btnCrearBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCrearBGLayout.setVerticalGroup(
            btnCrearBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnCrearBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Color gris = new Color(204,204,204);
    
    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        // Control de campo NOMBRE vacío.
        if (txtNombre.getText().equals("") || txtNombre.getText().equals("Ingrese un nombre")){
            txtNombre.setText("**Ingrese un nombre**");
            txtNombre.setForeground(Color.red);
        }
        
        // Control de campo DESCUENTO vacío.
        if (txtDescuento.getText().equals("") || txtDescuento.getText().equals("Ingrese el porcentaje a descontar")){
            txtDescuento.setText("**Ingrese un descuento**");
            txtDescuento.setForeground(Color.red);
        }
        
        // Control de campo DESCRIPCIÓN vacío.
        if (txtareaDescripcion.getText().equals("") || txtareaDescripcion.getText().equals("Ingrese una descripción")){
            txtareaDescripcion.setText("**Ingrese una descripción**");
            txtareaDescripcion.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // Vaciar txtField al hacer click.
        if (txtNombre.getText().equals("Ingrese un nombre") || txtNombre.getText().equals("**Ingrese un nombre**")){
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
         // Rellenar el otro txtField al hacer click si está vacío.
        if(txtDescuento.getText().equals("")){
            txtDescuento.setText("Ingrese el porcentaje a descontar");
            txtDescuento.setForeground(gris);
       }
        // Rellenar el txtArea al hacer click si está vacío.
        if(txtareaDescripcion.getText().equals("")){
            txtareaDescripcion.setText("Ingrese una descripción");
            txtareaDescripcion.setForeground(gris);
       }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtDescuentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescuentoMousePressed
         // Vaciar txtField al hacer click.
        if (txtDescuento.getText().equals("Ingrese el porcentaje a descontar") || txtDescuento.getText().equals("**Ingrese un descuento**")){
            txtDescuento.setText("");
            txtDescuento.setForeground(Color.black);
        }
        // Rellenar el otro txtField al hacer click si está vacío.
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese un nombre");
            txtNombre.setForeground(gris);
        }
        
         // Vaciar txtArea al hacer click.
        if(txtareaDescripcion.getText().equals("")){
            txtareaDescripcion.setText("Ingrese una descripción");
            txtareaDescripcion.setForeground(gris);
       }
    }//GEN-LAST:event_txtDescuentoMousePressed

    private void txtInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInicioMouseClicked
        // TODO add your handling code here:
        if (txtInicio.getText().equals("dd/mm/yyyy")){
            txtInicio.setText("");
            txtInicio.setForeground(Color.black);
        }
        dateChooserInicio.showPopup(this, 100, 100);
    }//GEN-LAST:event_txtInicioMouseClicked

    private void txtareaDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtareaDescripcionMouseClicked

        if (txtareaDescripcion.getText().equals("Ingrese una descripción") || txtareaDescripcion.getText().equals("**Ingrese una descripción**")){
            txtareaDescripcion.setText("");
            txtareaDescripcion.setForeground(Color.black);
        }
        
        // Rellenar el otro txtField al hacer click si está vacío.
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese un nombre");
            txtNombre.setForeground(gris);
        }
        
        // Rellenar el otro txtField al hacer click si está vacío.
        if(txtDescuento.getText().equals("")){
            txtDescuento.setText("Ingrese el porcentaje a descontar");
            txtDescuento.setForeground(gris);
       }
    }//GEN-LAST:event_txtareaDescripcionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCuponeraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCuponeraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCuponeraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCuponeraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearCuponeraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCrear;
    private javax.swing.JPanel btnCrearBG;
    private com.raven.datechooser.DateChooser dateChooserFin;
    private com.raven.datechooser.DateChooser dateChooserInicio;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtareaDescripcion;
    // End of variables declaration//GEN-END:variables
}
