/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygym.presentacion.forms;

/**
 *
 * @author mandi
 */
public class showActividadInfoForm extends javax.swing.JFrame {

    /**
     * Creates new form showActividadInfoForm
     */
    public showActividadInfoForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCuponeras = new javax.swing.JComboBox<>();
        cmbClases = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrollActividad = new javax.swing.JScrollPane();
        txaDescripcionActividad = new javax.swing.JTextArea();
        campoNombre = new javax.swing.JLabel();
        campoCosto = new javax.swing.JLabel();
        campoDuracion = new javax.swing.JLabel();
        campoFechaAlta = new javax.swing.JLabel();
        panelCuponeras = new javax.swing.JPanel();
        scrollCuponera = new javax.swing.JScrollPane();
        txaDescripcionCuponera = new javax.swing.JTextArea();
        campoVigenciaCuponera = new javax.swing.JLabel();
        campoDescuentoCuponera1 = new javax.swing.JLabel();
        campoNombreCuponera = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelClases = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        campoNombreClase = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoFechaClase = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        campoProfesorClase = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoCapacidadMinima = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        campoCapacidadMaxima = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        campoURL = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        campoFechaAltaClase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(4, 37, 58));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Información de la Actividad");
        bgPanel.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 870, 29));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuponeras Asociadas");
        bgPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 160, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clases Asociadas");
        bgPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 160, -1));

        cmbCuponeras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Item" }));
        cmbCuponeras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuponerasActionPerformed(evt);
            }
        });
        bgPanel.add(cmbCuponeras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, -1));

        cmbClases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Item" }));
        bgPanel.add(cmbClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 160, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de Alta al Sistema:");
        bgPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");
        bgPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripción:");
        bgPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Duración en Minutos:");
        bgPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Costo:");
        bgPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, -1));
        bgPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 870, 10));

        txaDescripcionActividad.setEditable(false);
        txaDescripcionActividad.setColumns(20);
        txaDescripcionActividad.setLineWrap(true);
        txaDescripcionActividad.setRows(5);
        scrollActividad.setViewportView(txaDescripcionActividad);

        bgPanel.add(scrollActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 210, -1));

        campoNombre.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoNombre.setText("xxxxxxxxxxxxxxx");
        bgPanel.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 260, 20));

        campoCosto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoCosto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoCosto.setText("xxxxxxxxxxxxxxx");
        bgPanel.add(campoCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 260, 20));

        campoDuracion.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoDuracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoDuracion.setText("xxxxxxxxxxxxxxx");
        bgPanel.add(campoDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 260, 20));

        campoFechaAlta.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoFechaAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoFechaAlta.setText("xxxxxxxxxxxxxxx");
        bgPanel.add(campoFechaAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 260, 20));

        panelCuponeras.setBackground(new java.awt.Color(249, 247, 247));
        panelCuponeras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaDescripcionCuponera.setEditable(false);
        txaDescripcionCuponera.setColumns(20);
        txaDescripcionCuponera.setLineWrap(true);
        txaDescripcionCuponera.setRows(5);
        scrollCuponera.setViewportView(txaDescripcionCuponera);

        panelCuponeras.add(scrollCuponera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, -1));

        campoVigenciaCuponera.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoVigenciaCuponera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoVigenciaCuponera.setText("xx/xx/xxx - xx/xx/xxx");
        panelCuponeras.add(campoVigenciaCuponera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 250, 20));

        campoDescuentoCuponera1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoDescuentoCuponera1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoDescuentoCuponera1.setText("xxxxxxxxxxxxxxx");
        panelCuponeras.add(campoDescuentoCuponera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 250, 20));

        campoNombreCuponera.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoNombreCuponera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoNombreCuponera.setText("xxxxxxxxxxxxxxx");
        panelCuponeras.add(campoNombreCuponera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 20));

        jLabel8.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre: ");
        panelCuponeras.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Descuento:");
        panelCuponeras.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Período de Vigencia:");
        panelCuponeras.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Descripción:");
        panelCuponeras.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        bgPanel.add(panelCuponeras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 400, 230));

        panelClases.setBackground(new java.awt.Color(249, 247, 247));
        panelClases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nombre: ");
        panelClases.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 20));

        campoNombreClase.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoNombreClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoNombreClase.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoNombreClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 230, 20));

        jLabel13.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fecha de la Clase:");
        panelClases.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        campoFechaClase.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoFechaClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoFechaClase.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoFechaClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, 20));

        jLabel14.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Profesor:");
        panelClases.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        campoProfesorClase.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoProfesorClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoProfesorClase.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoProfesorClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, 20));

        jLabel17.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Capacidad Mínima:");
        panelClases.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        campoCapacidadMinima.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoCapacidadMinima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoCapacidadMinima.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoCapacidadMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 230, 20));

        jLabel18.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Capacidad Máxima:");
        panelClases.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        campoCapacidadMaxima.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoCapacidadMaxima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoCapacidadMaxima.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoCapacidadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 230, 20));

        jLabel15.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("URL:");
        panelClases.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, -1));

        campoURL.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoURL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoURL.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, 20));

        jLabel16.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Fecha de Alta al Sistema:");
        panelClases.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        campoFechaAltaClase.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        campoFechaAltaClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoFechaAltaClase.setText("xxxxxxxxxxxxxxx");
        panelClases.add(campoFechaAltaClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, 20));

        bgPanel.add(panelClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 400, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCuponerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuponerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuponerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showActividadInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showActividadInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showActividadInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showActividadInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showActividadInfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel campoCapacidadMaxima;
    private javax.swing.JLabel campoCapacidadMinima;
    private javax.swing.JLabel campoCosto;
    private javax.swing.JLabel campoDescuentoCuponera1;
    private javax.swing.JLabel campoDuracion;
    private javax.swing.JLabel campoFechaAlta;
    private javax.swing.JLabel campoFechaAltaClase;
    private javax.swing.JLabel campoFechaClase;
    private javax.swing.JLabel campoNombre;
    private javax.swing.JLabel campoNombreClase;
    private javax.swing.JLabel campoNombreCuponera;
    private javax.swing.JLabel campoProfesorClase;
    private javax.swing.JLabel campoURL;
    private javax.swing.JLabel campoVigenciaCuponera;
    private javax.swing.JComboBox<String> cmbClases;
    private javax.swing.JComboBox<String> cmbCuponeras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPanel panelClases;
    private javax.swing.JPanel panelCuponeras;
    private javax.swing.JScrollPane scrollActividad;
    private javax.swing.JScrollPane scrollCuponera;
    private javax.swing.JTextArea txaDescripcionActividad;
    private javax.swing.JTextArea txaDescripcionCuponera;
    // End of variables declaration//GEN-END:variables
}
