/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygym.presentacion.forms;

import Actividad.ActividadBO;
import CuponeraXActividad.CuponeraXActividadBo;
import Actividad.dtos.ActividadDTO;
import CuponeraXActividad.DtCuponeraXActividad;
import Exceptions.CuponeraNotFoundException;
import Exceptions.InstitucionNotFoundException;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Institucion.DtInstitucion;
import Institucion.InstitucionBO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import utils.ComboItem;

/**
 *
 * @author mandi
 */
public class addActividadtoCuponera extends javax.swing.JFrame {
    
    public static HashMap<Integer, DtInstitucion> instituciones = new HashMap<>();
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    InstitucionBO insBO = new InstitucionBO();
    ActividadBO actBO = new ActividadBO();
    CuponeraXActividadBo cupxactBO = new CuponeraXActividadBo();

    
    int xMouse, yMouse;
    int idCupSeleccionada;
    int idActSeleccionada;
    /**
     * Creates new form agregarActividadACuponera
     */
    public addActividadtoCuponera() {
        initComponents();
        tablaInstituciones.getColumnModel().getColumn(0).setMinWidth(0);
        tablaInstituciones.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaInstituciones.getColumnModel().getColumn(0).setWidth(0);
        tablaInstituciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        llenarTablaInstituciones();
        this.setLocationRelativeTo(null);
    }
    
    // Segundo constructor, para recibir parámetros.
    public addActividadtoCuponera(Integer idCuponera) {
        initComponents();
        idCupSeleccionada = idCuponera;
        tablaInstituciones.getColumnModel().getColumn(0).setMinWidth(0);
        tablaInstituciones.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaInstituciones.getColumnModel().getColumn(0).setWidth(0);
        tablaInstituciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        separatorClases.setForeground(Color.gray);
        llenarTablaInstituciones();
        this.setLocationRelativeTo(null);
        
        cmbActividades.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                Object selectedItem = cmbActividades.getSelectedItem();
                if (selectedItem != null){
                    idActSeleccionada = Integer.parseInt(((ComboItem)selectedItem).getId());
                }
            }
        });
        
        txtClases.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                     e.consume();  // if it's not a number, ignore the event
                }
            }
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dragBar = new javax.swing.JLabel();
        btnMinimizarBG = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnExitBG = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaInstituciones = new javax.swing.JTable();
        btnSeleccionarActividadBG = new javax.swing.JPanel();
        btnSeleccionarActividad = new javax.swing.JLabel();
        cmbActividades = new javax.swing.JComboBox<>();
        lblInfo = new javax.swing.JLabel();
        lblHeader1 = new javax.swing.JLabel();
        lblClases = new javax.swing.JLabel();
        txtClases = new javax.swing.JTextField();
        separatorClases = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Actividad Deportiva a Cuponera");
        setMaximumSize(new java.awt.Dimension(670, 560));
        setMinimumSize(new java.awt.Dimension(670, 560));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 215, 215)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragBarMouseDragged(evt);
            }
        });
        dragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragBarMousePressed(evt);
            }
        });
        jPanel1.add(dragBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 20));

        btnMinimizarBG.setBackground(java.awt.Color.lightGray);

        btnMinimizar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setText("-");
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMinimizarBGLayout = new javax.swing.GroupLayout(btnMinimizarBG);
        btnMinimizarBG.setLayout(btnMinimizarBGLayout);
        btnMinimizarBGLayout.setHorizontalGroup(
            btnMinimizarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btnMinimizarBGLayout.setVerticalGroup(
            btnMinimizarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(btnMinimizarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 20));

        btnExitBG.setBackground(new java.awt.Color(174, 0, 51));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnExitBGLayout = new javax.swing.GroupLayout(btnExitBG);
        btnExitBG.setLayout(btnExitBGLayout);
        btnExitBGLayout.setHorizontalGroup(
            btnExitBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitBGLayout.setVerticalGroup(
            btnExitBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnExitBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 20));

        lblHeader.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(4, 37, 58));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Agregar Actividad Deportiva a Cuponera");
        jPanel1.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 29));

        scrollTabla.setBackground(new java.awt.Color(255, 255, 255));
        scrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        scrollTabla.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tablaInstituciones.setAutoCreateRowSorter(true);
        tablaInstituciones.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tablaInstituciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "Nombre", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInstituciones.setGridColor(new java.awt.Color(255, 255, 255));
        tablaInstituciones.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tablaInstituciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInstitucionesMouseClicked(evt);
            }
        });
        scrollTabla.setViewportView(tablaInstituciones);

        jPanel1.add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 630, 290));

        btnSeleccionarActividadBG.setBackground(new java.awt.Color(76, 131, 122));

        btnSeleccionarActividad.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnSeleccionarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarActividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionarActividad.setText("Agregar a la Cuponera");
        btnSeleccionarActividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarActividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarActividadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSeleccionarActividadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSeleccionarActividadMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnSeleccionarActividadBGLayout = new javax.swing.GroupLayout(btnSeleccionarActividadBG);
        btnSeleccionarActividadBG.setLayout(btnSeleccionarActividadBGLayout);
        btnSeleccionarActividadBGLayout.setHorizontalGroup(
            btnSeleccionarActividadBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSeleccionarActividad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btnSeleccionarActividadBGLayout.setVerticalGroup(
            btnSeleccionarActividadBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSeleccionarActividadBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeleccionarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSeleccionarActividadBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 220, -1));

        cmbActividades.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cmbActividades.setBorder(null);
        jPanel1.add(cmbActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 200, -1));

        lblInfo.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Actividades disponibles: (que no están en esta Cuponera)");
        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 670, -1));

        lblHeader1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(4, 37, 58));
        lblHeader1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHeader1.setText("Seleccione una Institución:");
        jPanel1.add(lblHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 29));

        lblClases.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblClases.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClases.setText("Cantidad de Clases");
        jPanel1.add(lblClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 120, 30));

        txtClases.setBorder(null);
        jPanel1.add(txtClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 200, 30));
        jPanel1.add(separatorClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void llenarTablaInstituciones(){
            instituciones = insBO.listarInstituciones();
            DefaultTableModel tableModel = (DefaultTableModel) tablaInstituciones.getModel();
            tableModel.setRowCount(0);
            instituciones.forEach((key, value) -> {
            DtInstitucion currentInstitucion = instituciones.get(key);

            tableModel.addRow(new Object[]{currentInstitucion.getId(), currentInstitucion.getNombre(), currentInstitucion.getDescripcion()});
        });    
    }
        
    // Agrega la actividad a la cuponera.
    private void btnSeleccionarActividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarActividadMouseClicked
        boolean error = false;
        
        if (cmbActividades.getSelectedItem() == null){
            JOptionPane.showMessageDialog(new JFrame(), "Debe seleccionar un item de las actividades disponibles.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        }
        
        if (txtClases.getText().equals("")){
            separatorClases.setForeground(Color.red);
            error=true;
        }
        
        if (!error){
            try {
                DtCuponeraXActividad dt = new DtCuponeraXActividad(Integer.parseInt(txtClases.getText()));
                System.out.println("tengo clases: " + dt.getCantClases());
                cupxactBO.agregarCupXAct(idActSeleccionada, idCupSeleccionada, dt);
                JOptionPane.showMessageDialog(new JFrame(), "¡Actividad insertada a la cuponera con exito!", "Actividad Insertada", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSeleccionarActividadMouseClicked

    private void btnSeleccionarActividadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarActividadMousePressed
        btnSeleccionarActividadBG.setBackground(new Color(103, 149, 142));
    }//GEN-LAST:event_btnSeleccionarActividadMousePressed

    private void btnSeleccionarActividadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarActividadMouseReleased
        btnSeleccionarActividadBG.setBackground(new Color(76,131,122));
    }//GEN-LAST:event_btnSeleccionarActividadMouseReleased

    private void tablaInstitucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInstitucionesMouseClicked
        // TODO add your handling code here:
        int selectedRowId = tablaInstituciones.getSelectedRow();
        if(selectedRowId == -1){
            JOptionPane.showMessageDialog(new JFrame(), "Error, seleccione una institución existente.", "Error", JOptionPane.ERROR_MESSAGE);
            cmbActividades.removeAllItems();
            return;
        }
        Object idObj = tablaInstituciones.getValueAt(selectedRowId, 0);
        int selectedInsitucionID = (Integer) idObj;
        cmbActividades.removeAllItems(); // Primero elimino todos los elems del combobox, para que solo se vean los de la institución seleccionada en el grid.
        //System.out.println("Id de la institucion seleccionada en la tabla: " + selectedInsitucionID);
        try {
            HashMap<Integer, ActividadDTO> actividades = actBO.listarByInstitucionNotInCuponeras(selectedInsitucionID, idCupSeleccionada,"Aceptada");
            actividades.forEach((key, value) -> {
                ActividadDTO currentActividadDTO = actividades.get(key);
                model.addElement(new ComboItem(key.toString(), currentActividadDTO.getNombre()));
            });
            cmbActividades.setModel(model);
            cmbActividades.setSelectedItem(null);
        } catch (Exception e) {
            cmbActividades.setSelectedItem(null);
            JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_tablaInstitucionesMouseClicked

    
    
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void dragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragBarMousePressed

    private void dragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragBarMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addActividadtoCuponera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addActividadtoCuponera().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JPanel btnExitBG;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JPanel btnMinimizarBG;
    private javax.swing.JLabel btnSeleccionarActividad;
    private javax.swing.JPanel btnSeleccionarActividadBG;
    private javax.swing.JComboBox<String> cmbActividades;
    private javax.swing.JLabel dragBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClases;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JSeparator separatorClases;
    private javax.swing.JTable tablaInstituciones;
    private javax.swing.JTextField txtClases;
    // End of variables declaration//GEN-END:variables
}
