/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygym.presentacion.forms;

import Actividad.ActividadBO;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.raven.datechooser.SelectedDate;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JTable;
import Actividad.dtos.ActividadCreateDTO;
import Institucion.DtInstitucion;
import Profesor.dtos.ProfesorDTO;
import Institucion.InstitucionBO;
import ParseDate.ParseDate;
import Profesor.ProfesorBO;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import mygym.presentacion.pages.Actividades;
import utils.ComboItem;


/**
 *
 * @author mandi
 */
public class createActividadForm extends javax.swing.JFrame{

   public static HashMap<Integer, DtInstitucion> instituciones = new HashMap<>();
   public static HashMap<Integer, ProfesorDTO> profesores = new HashMap<>(); 

    DefaultComboBoxModel modelInstituciones = new DefaultComboBoxModel();
    DefaultComboBoxModel modelProfesores = new DefaultComboBoxModel();
    ParseDate parse = new ParseDate();
    int xMouse, yMouse;
    Color gris = new Color(204,204,204);

    ActividadBO actBO = new ActividadBO();
    InstitucionBO insBO = new InstitucionBO();
    ProfesorBO profBO = new ProfesorBO();
    

    
    public createActividadForm() {
        initComponents();
        llenarCBoxInstituciones();
        llenarCBoxProfesores();
        
        this.setLocationRelativeTo(null);
        separatorNombre.setForeground(gris);
        separatorDuracion.setForeground(gris);
        scrollDescr.setViewportBorder(javax.swing.BorderFactory.createLineBorder(gris));
        txtNombre.setText("");
        txtDuracion.setText("");
        txtCosto.setText("");
        txtareaDescripcion.setText("");
        
        txtDuracion.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                     e.consume();  // if it's not a number, ignore the event
                }
            }
         });
        
        txtCosto.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                     e.consume();  // if it's not a number, ignore the event
                }
            }
         });
        
        txtNombre.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
                 if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )) {
                  e.consume();  // ignore the event if it's not an alphabet
              }
             }
          });
        txtFecha.enable(false);
    }
     
    private void llenarCBoxInstituciones(){
        cmbInstituciones.removeAllItems();
        instituciones = insBO.listarInstituciones();
        instituciones.forEach((key, value) -> {
            DtInstitucion currentInstitucion = instituciones.get(key);
            modelInstituciones.addElement(new ComboItem(key.toString(), currentInstitucion.getNombre()));
        });
        cmbInstituciones.setModel(modelInstituciones);
        cmbInstituciones.setSelectedItem(null);
    }    
   
        private void llenarCBoxProfesores(){
        cmbProfesores.removeAllItems();
        profesores = profBO.listarProfesores();
        profesores.forEach((key, value) -> {
            ProfesorDTO currentProf = profesores.get(key);
            modelProfesores.addElement(new ComboItem(key.toString(), currentProf.getNombre()));
        });
        cmbProfesores.setModel(modelProfesores);
        cmbProfesores.setSelectedItem(null);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserActual = new com.raven.datechooser.DateChooser();
        jPanel2 = new javax.swing.JPanel();
        dragBar = new javax.swing.JLabel();
        btnMinimizarBG = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnExitBG = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblInstitucion = new javax.swing.JLabel();
        cmbInstituciones = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        separatorNombre = new javax.swing.JSeparator();
        lblDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        separatorDuracion = new javax.swing.JSeparator();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        separatorCosto = new javax.swing.JSeparator();
        lblDescripcion = new javax.swing.JLabel();
        scrollDescr = new javax.swing.JScrollPane();
        txtareaDescripcion = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        separatorFecha = new javax.swing.JSeparator();
        btnCrearBG = new javax.swing.JPanel();
        btnCrear = new javax.swing.JLabel();
        lblProfesor = new javax.swing.JLabel();
        cmbProfesores = new javax.swing.JComboBox<>();

        dateChooserActual.setToolTipText("");
        dateChooserActual.setEnabled(false);
        dateChooserActual.setFocusable(false);
        dateChooserActual.setName(""); // NOI18N
        dateChooserActual.setRequestFocusEnabled(false);
        dateChooserActual.setTextRefernce(txtFecha);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear cuponera");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 540));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 215, 215)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragBarMouseDragged(evt);
            }
        });
        dragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragBarMousePressed(evt);
            }
        });
        jPanel2.add(dragBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 20));

        btnMinimizarBG.setBackground(java.awt.Color.lightGray);

        btnMinimizar.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setText("-");
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnMinimizarBGLayout = new javax.swing.GroupLayout(btnMinimizarBG);
        btnMinimizarBG.setLayout(btnMinimizarBGLayout);
        btnMinimizarBGLayout.setHorizontalGroup(
            btnMinimizarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btnMinimizarBGLayout.setVerticalGroup(
            btnMinimizarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel2.add(btnMinimizarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, 20));

        btnExitBG.setBackground(new java.awt.Color(174, 0, 51));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnExitBGLayout = new javax.swing.GroupLayout(btnExitBG);
        btnExitBG.setLayout(btnExitBGLayout);
        btnExitBGLayout.setHorizontalGroup(
            btnExitBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitBGLayout.setVerticalGroup(
            btnExitBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(btnExitBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 20));

        lblHeader.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(4, 37, 58));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Alta de Actividad Deportiva");
        jPanel2.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, 29));

        lblInstitucion.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblInstitucion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInstitucion.setText("Institucion");
        jPanel2.add(lblInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, 30));

        cmbInstituciones.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cmbInstituciones.setFocusable(false);
        cmbInstituciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInstitucionesActionPerformed(evt);
            }
        });
        jPanel2.add(cmbInstituciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, 30));

        lblNombre.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 50, 30));

        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, 30));
        jPanel2.add(separatorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 210, 20));

        lblDuracion.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblDuracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDuracion.setText("Duración (minutos)");
        jPanel2.add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 30));

        txtDuracion.setToolTipText("");
        txtDuracion.setBorder(null);
        jPanel2.add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 210, 30));
        jPanel2.add(separatorDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 210, 20));

        lblCosto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblCosto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCosto.setText("Costo");
        jPanel2.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 40, 30));

        txtCosto.setToolTipText("");
        txtCosto.setBorder(null);
        jPanel2.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 210, 30));
        jPanel2.add(separatorCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, 20));

        lblDescripcion.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescripcion.setText("Descripción");
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 70, 30));

        scrollDescr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        scrollDescr.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 249, 248)));

        txtareaDescripcion.setColumns(20);
        txtareaDescripcion.setLineWrap(true);
        txtareaDescripcion.setRows(5);
        txtareaDescripcion.setBorder(null);
        scrollDescr.setViewportView(txtareaDescripcion);

        jPanel2.add(scrollDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 210, -1));

        lblFecha.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha del Sistema");
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 150, 30));

        txtFecha.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(null);
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 130, 20));
        jPanel2.add(separatorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, 20));

        btnCrearBG.setBackground(new java.awt.Color(76, 131, 122));

        btnCrear.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrear.setText("Crear");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCrearBGLayout = new javax.swing.GroupLayout(btnCrearBG);
        btnCrearBG.setLayout(btnCrearBGLayout);
        btnCrearBGLayout.setHorizontalGroup(
            btnCrearBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCrearBGLayout.setVerticalGroup(
            btnCrearBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnCrearBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        lblProfesor.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        lblProfesor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfesor.setText("Profesor");
        jPanel2.add(lblProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, 30));

        cmbProfesores.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        cmbProfesores.setFocusable(false);
        jPanel2.add(cmbProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        boolean error = false;
        
        if (cmbInstituciones.getSelectedItem() == null){
            JOptionPane.showMessageDialog(new JFrame(), "Seleccione una Insitución.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (cmbProfesores.getSelectedItem() == null){
            JOptionPane.showMessageDialog(new JFrame(), "Seleccione un Profesor.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Control de campo NOMBRE vacío.
        if (txtNombre.getText().equals("")){
            separatorNombre.setForeground(Color.red);
            error=true;
        }
        
        // Control de campo DURACIÓN vacío.
        if (txtDuracion.getText().equals("")){
            separatorDuracion.setForeground(Color.red);
            error=true;
        }
        
        // Control de campo COSTO vacío.
        if (txtCosto.getText().equals("")){
            separatorCosto.setForeground(Color.red);
            error=true;
        }
        
        // Control de campo DESCRIPCIÓN vacío.
        if (txtareaDescripcion.getText().equals("")){
            scrollDescr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            scrollDescr.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            error=true;
        }
         
        if (!error){
            
            Object selectedItemInsti = cmbInstituciones.getSelectedItem();
            int selectedInstitucionId = Integer.parseInt(((ComboItem)selectedItemInsti).getId());           
            
            Object selectedItemProf = cmbInstituciones.getSelectedItem();
            int selectedProfId = Integer.parseInt(((ComboItem)selectedItemProf).getId());           
            
            SelectedDate fActual = dateChooserActual.getSelectedDate();
            Date fecha = parse.parseDate(fActual.getYear() + "-" + fActual.getMonth() + "-" + fActual.getDay());
            ActividadCreateDTO act = new ActividadCreateDTO(selectedInstitucionId, selectedProfId, Float.parseFloat(txtCosto.getText()), txtNombre.getText(), txtareaDescripcion.getText(), fecha, Integer.parseInt(txtDuracion.getText())); 
            try {
                actBO.crear(act, selectedInstitucionId, selectedProfId);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtNombre.setText("");
            txtDuracion.setText("");
            txtCosto.setText("");
            txtareaDescripcion.setText("");
            separatorNombre.setForeground(gris);
            separatorDuracion.setForeground(gris);
            separatorCosto.setForeground(gris);
            scrollDescr.setViewportBorder(javax.swing.BorderFactory.createLineBorder(gris));
            dispose();
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void dragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragBarMouseDragged

    private void dragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragBarMousePressed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void cmbInstitucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstitucionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbInstitucionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createActividadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createActividadForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCrear;
    private javax.swing.JPanel btnCrearBG;
    private javax.swing.JLabel btnExit;
    private javax.swing.JPanel btnExitBG;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JPanel btnMinimizarBG;
    private javax.swing.JComboBox<String> cmbInstituciones;
    private javax.swing.JComboBox<String> cmbProfesores;
    private com.raven.datechooser.DateChooser dateChooserActual;
    private javax.swing.JLabel dragBar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProfesor;
    private javax.swing.JScrollPane scrollDescr;
    private javax.swing.JSeparator separatorCosto;
    private javax.swing.JSeparator separatorDuracion;
    private javax.swing.JSeparator separatorFecha;
    private javax.swing.JSeparator separatorNombre;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtareaDescripcion;
    // End of variables declaration//GEN-END:variables
}
