/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mygym.presentacion.pages;

import java.awt.Color;
import java.awt.Toolkit;
import mygym.presentacion.components.AgregarRegistros;
import mygym.presentacion.components.ChooseInstitucion;
import mygym.presentacion.forms.AddClaseForm;

/**
 *
 * @author maximilianooliverasilva
 */
public class Clase extends javax.swing.JPanel {

    /**
     * Creates new form Clase
     */
    AddClaseForm form = new AddClaseForm();
    AgregarRegistros ar = new AgregarRegistros();

    public Clase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnAltaClase = new javax.swing.JButton();
        btnAltaRegistro = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(720, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(215, 215, 215)));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 69, 87));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clases");
        pnlHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        btnConsultar.setBackground(new java.awt.Color(76, 131, 122));
        btnConsultar.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setToolTipText("");
        btnConsultar.setBorder(null);
        btnConsultar.setFocusPainted(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlHeader.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 200, 40));

        btnAltaClase.setBackground(new java.awt.Color(76, 131, 122));
        btnAltaClase.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnAltaClase.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaClase.setText("Alta de Clase");
        btnAltaClase.setToolTipText("");
        btnAltaClase.setBorder(null);
        btnAltaClase.setFocusPainted(false);
        btnAltaClase.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAltaClase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAltaClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaClaseActionPerformed(evt);
            }
        });
        pnlHeader.add(btnAltaClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, 40));

        btnAltaRegistro.setBackground(new java.awt.Color(76, 131, 122));
        btnAltaRegistro.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnAltaRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnAltaRegistro.setText("Agregar Registro");
        btnAltaRegistro.setToolTipText("");
        btnAltaRegistro.setBorder(null);
        btnAltaRegistro.setFocusPainted(false);
        btnAltaRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAltaRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAltaRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaRegistroMouseClicked(evt);
            }
        });
        btnAltaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaRegistroActionPerformed(evt);
            }
        });
        pnlHeader.add(btnAltaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 40, 200, 40));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaClaseActionPerformed
        if (!form.isVisible()) {
            form.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaClaseActionPerformed

    private void btnAltaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaRegistroActionPerformed
        if (!ar.isVisible()) {
            ar.setVisible(true);
        }
        //ÇÇar.setLocationRelativeTo(null);
        //ar.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaRegistroActionPerformed

    private void btnAltaRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaRegistroMouseClicked

    }//GEN-LAST:event_btnAltaRegistroMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ChooseInstitucion chooseInstitucion = new ChooseInstitucion();
        chooseInstitucion.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaClase;
    private javax.swing.JButton btnAltaRegistro;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
