/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mygym.presentacion.pages;
import mygym.presentacion.forms.crearCuponeraForm;
import java.awt.Color;
import mygym.presentacion.forms.addActividadtoCuponera;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Cuponera.CuponeraBo;
import Cuponera.DtCuponera;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import mygym.presentacion.forms.showInfoCuponera;
import utils.RenderFoto;

/**
 *
 * @author maximilianooliverasilva
 */
public class Cuponeras extends javax.swing.JPanel {

    CuponeraBo cupBo = new CuponeraBo();
    crearCuponeraForm formCrear = new crearCuponeraForm();
    public static HashMap<Integer, DtCuponera> cuponeras = new HashMap<Integer, DtCuponera>();

    public Cuponeras() {
        initComponents();
        tablaCuponeras.getColumnModel().getColumn(1).setMinWidth(1);
        tablaCuponeras.getColumnModel().getColumn(1).setMaxWidth(1);
        tablaCuponeras.getColumnModel().getColumn(1).setWidth(1);
        tablaCuponeras.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaCuponeras.setRowHeight(50);
        llenarTabla();
        formCrear.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                llenarTabla();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnCrearBG = new javax.swing.JPanel();
        btnCrear = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaCuponeras = new javax.swing.JTable();
        btnAgregarBG = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(720, 540));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(215, 215, 215)));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(41, 69, 87));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Cuponeras");
        bgPanel.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        btnCrearBG.setBackground(new java.awt.Color(76, 131, 122));

        btnCrear.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrear.setText("Alta de Cuponera");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCrearMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnCrearBGLayout = new javax.swing.GroupLayout(btnCrearBG);
        btnCrearBG.setLayout(btnCrearBGLayout);
        btnCrearBGLayout.setHorizontalGroup(
            btnCrearBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        btnCrearBGLayout.setVerticalGroup(
            btnCrearBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(btnCrearBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 160, -1));

        scrollTabla.setBackground(new java.awt.Color(255, 255, 255));
        scrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        scrollTabla.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tablaCuponeras.setAutoCreateRowSorter(true);
        tablaCuponeras.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        tablaCuponeras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Foto", "id", "Nombre", "Descuento", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuponeras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaCuponeras.setGridColor(new java.awt.Color(255, 255, 255));
        tablaCuponeras.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tablaCuponeras.setUpdateSelectionOnSort(false);
        scrollTabla.setViewportView(tablaCuponeras);
        if (tablaCuponeras.getColumnModel().getColumnCount() > 0) {
            tablaCuponeras.getColumnModel().getColumn(0).setResizable(false);
            tablaCuponeras.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaCuponeras.getColumnModel().getColumn(1).setResizable(false);
            tablaCuponeras.getColumnModel().getColumn(2).setResizable(false);
            tablaCuponeras.getColumnModel().getColumn(3).setResizable(false);
        }

        bgPanel.add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 640, 350));

        btnAgregarBG.setBackground(new java.awt.Color(76, 131, 122));

        btnAgregar.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("Agregar Actividad a la Cuponera");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAgregarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarBGLayout = new javax.swing.GroupLayout(btnAgregarBG);
        btnAgregarBG.setLayout(btnAgregarBGLayout);
        btnAgregarBGLayout.setHorizontalGroup(
            btnAgregarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        btnAgregarBGLayout.setVerticalGroup(
            btnAgregarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarBGLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(btnAgregarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 310, -1));

        btnConsultar.setBackground(new java.awt.Color(76, 131, 122));
        btnConsultar.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar Información");
        btnConsultar.setToolTipText("");
        btnConsultar.setBorder(null);
        btnConsultar.setFocusPainted(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        bgPanel.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 310, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla(){
        cuponeras = cupBo.listarCuponeras();
        DefaultTableModel modeloDatos = (DefaultTableModel) tablaCuponeras.getModel();
        modeloDatos.setRowCount(0);
        cuponeras.forEach((key, value) -> {
            DtCuponera currentCuponera = cuponeras.get(key);
            RenderFoto photoCell = new RenderFoto();
            photoCell.setHorizontalAlignment(SwingConstants.CENTER);
            tablaCuponeras.getColumnModel().getColumn(0).setCellRenderer(photoCell);
            String filePath = "";
            if (value.getImage() != null) {
                filePath = value.getImage().getAbsolutePath();
            }
            modeloDatos.addRow(new Object[]{filePath, currentCuponera.getId(), currentCuponera.getNombre(), currentCuponera.getDescripcion(), currentCuponera.getDescuento(), currentCuponera.getPrecio()});
        });
    }

    
   
    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        if (!formCrear.isVisible()) {
                // Focus LOST para el form.
                formCrear.setVisible(true);
                //formCrear.transferFocus();
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMousePressed
        btnCrearBG.setBackground(new Color(103, 149, 142));
    }//GEN-LAST:event_btnCrearMousePressed

    private void btnCrearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseReleased
        btnCrearBG.setBackground(new Color(76,131,122));
    }//GEN-LAST:event_btnCrearMouseReleased

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        int selectedRowId = tablaCuponeras.getSelectedRow();
        if(selectedRowId == -1){
            JOptionPane.showMessageDialog(new JFrame(), "Error, seleccione una cuponera existente.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Object idObj = tablaCuponeras.getValueAt(selectedRowId, 1);
        int id = (Integer) idObj;
        
        addActividadtoCuponera formAgregar = new addActividadtoCuponera(id);

        // Event listener para que cuando se cierra el form de agregar act a cuponera, se actualice la tabla con la colección local instantaneamente.
        formAgregar.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                llenarTabla();
            }
        });
        
        if (!formAgregar.isVisible()) {
           formAgregar.setVisible(true);
        }
        
    }//GEN-LAST:event_btnAgregarMouseClicked

    // Cambiar de color el botón al presionar.
    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        btnAgregarBG.setBackground(new Color(103, 149, 142));
    }//GEN-LAST:event_btnAgregarMousePressed

    // Cambiar de color el botón al presionar.
    private void btnAgregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseReleased
        btnAgregarBG.setBackground(new Color(76,131,122));
    }//GEN-LAST:event_btnAgregarMouseReleased

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // ACTUALIZAR GRID
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        int selectedRowId = tablaCuponeras.getSelectedRow();
        if(selectedRowId == -1){
            JOptionPane.showMessageDialog(new JFrame(), "Error, seleccione una cuponera existente.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Object idObj = tablaCuponeras.getValueAt(selectedRowId, 1);
        int selectedCuponeraID = (Integer) idObj;
        DtCuponera selectedCup = cuponeras.get(selectedCuponeraID); // PASARLE ESTE DT POR EL CONSTRUCTOR DEL FORM
        if (selectedCup != null){
            showInfoCuponera formInfo = new showInfoCuponera(selectedCup);
            if (!formInfo.isVisible()) {
                formInfo.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "Error, seleccione una cuponera existente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JPanel btnAgregarBG;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel btnCrear;
    private javax.swing.JPanel btnCrearBG;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaCuponeras;
    // End of variables declaration//GEN-END:variables
}
